import { getYears } from '../../utills/getYears';

export const carBrand: string[] = [
  'Toyota',
  'Hyundai',
  'Nissan',
  'Audi',
  'Tesla',
  'Ford',
  'Land Rover',
  'Honda',
  'Suzuki',
  'Mitsubishi',
  'BMW',
  'Mercedes Benz',
  'Volkswagen',
  'Chevrolet',
  'Lexus',
  'Jaguar',
  'Kia',
  'Mazda',
  'Subaru',
  'Bentley',
  'Peugeot',
  'Renault',
  'Volvo',
  'Jeep',
  'Chrysler',
  'Dodge',
  'Cadillac',
  'GMC',
  'Acura',
  'Infiniti',
  'Alfa Romeo',
  'Maserati',
  'Lincoln',
  'Citroën',
  'Fiat',
  'Mini',
  'Skoda',
  'Genesis',
  'RAM',
  'Hummer',
  'Saab',
  'Seat',
  'Proton',
  'Tata',
  'Opel',
] as const;

export const carCategory: string[] = [
  'Sedan',
  'SUV',
  'Coupe',
  'Convertible',
  'Electric',
  'Sports Car',
  'Hybrid',
  'Jeep',
  'Luxury',
  'Hatchback',
  'Pickup Truck',
  'Van',
  'Minivan',
  'Wagon',
  'Crossover',
  'Muscle Car',
  'Roadster',
  'Diesel',
  'Off-Road',
  'Supercar',
  'Classic Car',
  'Limousine',
  'Station Wagon',
  'Microcar',
  'Targa Top',
  'Camper Van',
  'Utility Vehicle',
  'Compact Car',
  'Pony Car',
] as const;

export const condition: string[] = [
  'New',
  'Used',
  'Certified Pre-Owned',
] as const;

export const seatingCapacity: string[] = [
  '2',
  '4',
  '5',
  '6',
  '7',
  '8',
  '9',
  '10+',
] as const;

type TCarBrandLogo = Record<string, string>;
export const carBrandLogo: TCarBrandLogo = {
  Audi: 'https://i.ibb.co.com/twsHWLjS/audi.png',
  Ford: 'https://i.ibb.co.com/rXJfkMD/ford.png',
  Honda: 'https://i.ibb.co.com/xKBRH0cH/honda.png',
  Hyundai: 'https://i.ibb.co.com/MxYKvwph/hyundai.png',
  'Land Rover': 'https://i.ibb.co.com/Kx44z8tT/land-rover.png',
  Mitsubishi: 'https://i.ibb.co.com/yFbhpqK1/mitsubishi.png',
  Nissan: 'https://i.ibb.co.com/QvHRZwcx/nisaan.png',
  Suzuki: 'https://i.ibb.co.com/KxKNWFC2/suzuki.png',
  Tesla: 'https://i.ibb.co.com/Ng9dbzQ8/tesla.png',
  Toyota: 'https://i.ibb.co.com/wfx5cHj/toyota.png',
  Proton: 'https://i.ibb.co.com/0y87NrBw/proton.png',
  Tata: 'https://i.ibb.co.com/6Jw0K24Y/tata.png',
  Seat: 'https://i.ibb.co.com/d0BXZFpJ/seat.png',
  Saab: 'https://i.ibb.co.com/RT3GvPLk/saab.png',
  Hummer: 'https://i.ibb.co.com/kV6d2QfL/Hummer.png',
  RAM: 'https://i.ibb.co.com/Ps00tN1J/ram.png',
  Genesis: 'https://i.ibb.co.com/5g9mXLmP/genesis.png',
  Skoda: 'https://i.ibb.co.com/F4tm2HB3/scoda.png',
  Mini: 'https://i.ibb.co.com/qFXXwRXK/mini.png',
  Fiat: 'https://i.ibb.co.com/mCZ5tmpQ/fiat.png',
  Citroën: 'https://i.ibb.co.com/vvD7zyC7/citrone.png',
  Lincoln: 'https://i.ibb.co.com/93c27Jbc/lincoln.png',
  Maserati: 'https://i.ibb.co.com/jPkkLC8h/mesarti.png',
  'Alfa Romeo': 'https://i.ibb.co.com/5hF9LQGc/alfa-romep.png',
  Infiniti: 'https://i.ibb.co.com/99HTWJyL/infiniti.png',
  Acura: 'https://i.ibb.co.com/7tFYK8sN/acura.png',
  GMC: 'https://i.ibb.co.com/zwbMWPn/gmc.png',
  Cadillac: 'https://i.ibb.co.com/YBD4kfzT/cadilac.png',
  Dodge: 'https://i.ibb.co.com/ccrVxmKK/dodge.png',
  Chrysler: 'https://i.ibb.co.com/1YGnkkMh/Chrysler.png',
  Jeep: 'https://i.ibb.co.com/bRRCCr20/jeep.png',
  Volvo: 'https://i.ibb.co.com/kVCfsYDL/volvo.png',
  Renault: 'https://i.ibb.co.com/tTLL2D58/renault.png',
  Peugeot: 'https://i.ibb.co.com/GfmrH8c4/peugeot.png',
  Bentley: 'https://i.ibb.co.com/ks0MdcSW/bently.png',
  Subaru: 'https://i.ibb.co.com/tMvj8sMk/subaru.png',
  Mazda: 'https://i.ibb.co.com/4ntPpNZT/mazda.png',
  Kia: 'https://i.ibb.co.com/Tqp6zZPb/kia.png',
  Jaguar: 'https://i.ibb.co.com/JLv5n40/jaguar.png',
  Lexus: 'https://i.ibb.co.com/C37K7GL1/lexus.png',
  Chevrolet: 'https://i.ibb.co.com/FLn9rVcy/chevrolet.png',
  Volkswagen: 'https://i.ibb.co.com/kVvDZX4x/volkswagon.png',
  'Mercedes Benz': 'https://i.ibb.co.com/Wm7Tmf6/Mercedes.png',
  BMW: 'https://i.ibb.co.com/F4Q5MbKD/bmw.png',
  Opel: 'https://ibb.co.com/M5WvdFnh',
} as const;

export const carSearchAbleFields = ['brand', 'model', 'country', 'category'];

export const years = getYears();
